spring:
  application:
    name: hotels
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotels}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  flyway:
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true