CREATE TABLE IF NOT EXISTS hotels (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  country VARCHAR(100),
  city VARCHAR(100),
  street VARCHAR(100),
  building VARCHAR(100),
  rating DECIMAL(2, 1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);